# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code.xci
# IP: The module: 'ram_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_code'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code.xci
# IP: The module: 'ram_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_code'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
